import {
    Container,
    Description,
    Image,
    InlineFrame,
    Label,
    ListView,
} from '@ifrc-go/ui';
import { useTranslation } from '@ifrc-go/ui/hooks';

import arcLogo from '#assets/icons/arc_logo.png';
import aurcLogo from '#assets/icons/aurc_logo.svg';
import brcLogo from '#assets/icons/brc_logo.png';
import crcLogo from '#assets/icons/crc_logo.png';
import dnkLogo from '#assets/icons/dnk_logo.png';
import ericLogo from '#assets/icons/ericsson_logo.png';
import esprcLogo from '#assets/icons/esp_logo.svg';
import frcLogo from '#assets/icons/frc_logo.png';
import jrcLogo from '#assets/icons/jrc_logo.png';
import nlrcLogo from '#assets/icons/nlrc_logo.jpg';
import pdcLogo from '#assets/icons/pdc_logo.svg';
import swissLogo from '#assets/icons/swiss.svg';
import usAidLogo from '#assets/icons/us_aid.svg';
import Link from '#components/Link';
import Page from '#components/Page';
import { useRequest } from '#utils/restRequest';

import VideoList from './VideoList';

import i18n from './i18n.json';
import styles from './styles.module.css';

// eslint-disable-next-line import/prefer-default-export
export function Component() {
    const strings = useTranslation(i18n);
    const { response: contactsResponse } = useRequest({
        url: '/api/v2/main_contact/',
    });

    return (
        <Page
            title={strings.aboutResourcesTitle}
            heading={strings.aboutResources}
            description={strings.resourcesDescription}
            info={(
                <InlineFrame
                    className={styles.introductionVideo}
                    title="GO introduction video"
                    src="https://www.youtube.com/embed/dwPsQzla9A4"
                    allowFullScreen
                />
            )}
        >
            <div className={styles.reservedSpace} />
            <Container
                heading={strings.goUserGuidance}
                spacing="xl"
                withCenteredHeading
            >
                <ListView
                    layout="grid"
                    minGridColumnSize="20rem"
                >
                    <Container
                        heading={strings.goReferenceMaterial}
                        headerDescription={strings.goUserReferenceMaterial}
                        withHeaderBorder
                        withBackground
                        withPadding
                        withShadow
                        headingLevel={5}
                    >
                        <ListView
                            layout="grid"
                            withSpacingOpticalCorrection
                        >
                            <Link
                                href="https://go-wiki.ifrc.org"
                                external
                                withLinkIcon
                            >
                                {strings.visitGoWiki}
                            </Link>
                            <Link
                                href="https://ifrcgoproject.medium.com/"
                                external
                                withLinkIcon
                            >
                                {strings.goBlog}
                            </Link>
                            <Link
                                href="https://app.powerbi.com/view?r=eyJrIjoiMmE2OTg5ZDgtYzMyNC00NjQ1LWJkZWUtMDI1ZDc5M2Q5ZDFlIiwidCI6ImEyYjUzYmU1LTczNGUtNGU2Yy1hYjBkLWQxODRmNjBmZDkxNyIsImMiOjh9"
                                external
                                withLinkIcon
                            >
                                {strings.goUserAnalytics}
                            </Link>
                            <Link
                                href="https://ifrcorg.sharepoint.com/:b:/s/IFRCSharing/EQraprcbhQdGgH1L8tSQXFAByvRgyoBRfW46HTMh71Nzlw?e=dMQIr8"
                                external
                                withLinkIcon
                            >
                                {strings.goWorkplan}
                            </Link>
                            <Link
                                href="https://ifrcgoproject.medium.com/information-saves-lives-scaling-data-analytics-in-the-ifrc-network-fd3686718f9c"
                                external
                                withLinkIcon
                            >
                                {strings.ifrcStrategicDirection}
                            </Link>
                            <Link
                                href="https://66557be6b68dacbf0a96db23-zctxglhsnk.chromatic.com/"
                                external
                                withLinkIcon
                            >
                                {strings.goUIStorybook}
                            </Link>
                        </ListView>
                    </Container>
                </ListView>
            </Container>
            <div />
            <Container
                heading={strings.referenceVideos}
                withCenteredHeading
                spacing="xl"
            >
                <VideoList />
            </Container>
            <div />
            <Container
                heading={strings.ifrcResources}
                spacing="xl"
                withCenteredHeading
            >
                <ListView
                    layout="grid"
                    numPreferredGridColumns={3}
                >
                    <Container
                        heading={strings.aboutSurgeLinks}
                        withHeaderBorder
                        withPadding
                        withBackground
                        withShadow
                        headingLevel={5}
                    >
                        <ListView
                            layout="block"
                            withSpacingOpticalCorrection
                            spacing="sm"
                        >
                            <Link
                                href="https://docs.google.com/spreadsheets/d/1F-78qDc8vdh5hli5FLFeyTvlFQgw19OqZXMR50TQ1C0/edit?usp=sharing"
                                external
                                withLinkIcon
                            >
                                {strings.aboutSurgeEvents}
                            </Link>
                            <Link
                                href="https://rcrcsims.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutSIMS}
                            </Link>
                            <Link
                                href="https://www.cbsrc.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutCommunitySurveillance}
                            </Link>
                            <Link
                                href="https://go.ifrc.org/surge/catalogue/overview"
                                external
                                withLinkIcon
                            >
                                {strings.aboutCoS}
                            </Link>
                            <Link
                                href="https://surgelearning.ifrc.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutSurgeLearning}
                            </Link>
                            <Link
                                href="https://surgelearning.ifrc.org/resources/core-competency-framework-surge-personnel"
                                external
                                withLinkIcon
                            >
                                {strings.aboutCoreCompetencyFramework}
                            </Link>
                        </ListView>
                    </Container>
                    <Container
                        heading={strings.aboutGuidanceMaterial}
                        withHeaderBorder
                        withPadding
                        withBackground
                        withShadow
                        headingLevel={5}
                    >
                        <ListView
                            layout="block"
                            withSpacingOpticalCorrection
                            spacing="sm"
                        >
                            <Link
                                href="https://www.cash-hub.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutCashHub}
                            </Link>
                            <Link
                                href="https://www.communityengagementhub.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutCommunityHub}
                            </Link>
                            <Link
                                href="https://preparecenter.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutDisasterPreparednessCenter}
                            </Link>
                            <Link
                                href="https://preparecenter.org/toolkit/data-playbook-toolkit-v1/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutDataPlaybook}
                            </Link>
                        </ListView>
                    </Container>
                    <Container
                        heading={strings.aboutOtherResources}
                        withHeaderBorder
                        withPadding
                        withBackground
                        withShadow
                        headingLevel={5}
                    >
                        <ListView
                            layout="block"
                            withSpacingOpticalCorrection
                            spacing="sm"
                        >
                            <Link
                                href="https://www.ifrc.org/reference-centres/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutReferenceCenters}
                            </Link>

                            <Link
                                href="https://www.missingmaps.org/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutMissingMaps}
                            </Link>
                            <Link
                                href="https://data.ifrc.org/fdrs/"
                                external
                                withLinkIcon
                            >
                                {strings.aboutReportingSystem}
                            </Link>
                            <Link
                                href="https://ifrc.csod.com/client/ifrc/default.aspx"
                                external
                                withLinkIcon
                            >
                                {strings.aboutLearningPlatform}
                            </Link>
                            <Link
                                href="https://prddsgofilestorage.blob.core.windows.net/api/documents/Health/f872f96b01ab47d3853b301ebe17573d/Health_Mapping_Report_1.pdf"
                                external
                                withLinkIcon
                            >
                                {strings.aboutHealthMapping}
                            </Link>
                        </ListView>
                    </Container>
                </ListView>
            </Container>
            <div />
            <Container
                heading={strings.aboutContacts}
                spacing="xl"
                withCenteredHeading
            >
                <ListView
                    layout="block"
                    spacing="xl"
                >
                    <ListView
                        layout="grid"
                        numPreferredGridColumns={5}
                    >
                        {contactsResponse?.results?.map((contact) => (
                            <Container
                                key={contact.extent}
                                heading={contact.extent}
                                headingLevel={6}
                                withPadding
                                withShadow
                                withBackground
                            >
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <Label strong>
                                        {contact.name}
                                    </Label>
                                    <Link
                                        href={`mailto:${contact.email}`}
                                        external
                                        withLinkIcon
                                        withEllipsizedContent
                                    >
                                        {contact.email}
                                    </Link>
                                </ListView>
                            </Container>
                        ))}
                    </ListView>
                    <ListView
                        layout="block"
                        withSpacingOpticalCorrection
                        withCenteredContents
                        spacing="xs"
                    >
                        <Description withLightText>
                            {strings.aboutFurtherInfo}
                        </Description>
                        <Link
                            href="mailto:im@ifrc.org"
                            external
                            withLinkIcon
                            colorVariant="primary"
                            styleVariant="filled"
                        >
                            im@ifrc.org
                        </Link>
                    </ListView>
                </ListView>
            </Container>
            <div />
            <Container
                heading={strings.aboutGoFundingTitle}
                headerDescription={strings.aboutGoFundingDescription}
                withCenteredHeading
                withCenteredHeaderDescription
                spacing="xl"
            >
                <ListView
                    layout="grid"
                    numPreferredGridColumns={5}
                    spacing="lg"
                >
                    <Link
                        href="https://www.redcross.org/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={arcLogo}
                            alt={strings.redCrossImageAmericanAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.redcross.org.au/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={aurcLogo}
                            alt={strings.redCrossImageAustralianAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.redcross.org.uk/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={brcLogo}
                            alt={strings.redCrossImageBritishAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.redcross.ca/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={crcLogo}
                            alt={strings.redCrossImageCanadaAlt}
                        />
                    </Link>
                    <Link
                        href="https://en.rodekors.dk/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={dnkLogo}
                            alt={strings.redCrossImageDanishAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.redcross.fi/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={frcLogo}
                            alt={strings.redCrossImageFinnishAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.jrc.or.jp/english/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={jrcLogo}
                            alt={strings.redCrossImageJapaneseAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.rodekruis.nl/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={nlrcLogo}
                            alt={strings.redCrossImageNetherlandsAlt}
                        />
                    </Link>
                    <Link
                        href="https://www2.cruzroja.es/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={esprcLogo}
                            alt={strings.redCrossImageSpanishAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.ericsson.com/en"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={ericLogo}
                            alt={strings.ericImageAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.admin.ch/gov/de/start.html"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={swissLogo}
                            alt={strings.visitSwissImageAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.usaid.gov/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={usAidLogo}
                            alt={strings.visitUSAidImageAlt}
                        />
                    </Link>
                    <Link
                        href="https://www.pdc.org/"
                        external
                        styleVariant="transparent"
                    >
                        <Image
                            withContainedFit
                            withoutBackground
                            src={pdcLogo}
                            alt={strings.visitPDCImageAlt}
                        />
                    </Link>
                </ListView>
            </Container>
            <div />
        </Page>
    );
}

Component.displayName = 'Resources';
