import { useState } from 'react';
import {
    Container,
    Description,
    GridLayoutItem,
    ListView,
    Tab,
    TabList,
    TabPanel,
    Tabs,
} from '@ifrc-go/ui';
import { useTranslation } from '@ifrc-go/ui/hooks';

import DrefDecisionTreeCallout from '#components/domain/DrefDecisionTreeCallout';
import DrefDocumentLink from '#components/domain/DrefDocumentLink';
import DrefKeyResources from '#components/domain/DrefKeyResources';
import Faq from '#components/domain/Faq';
import FaqHeading from '#components/domain/Faq/FaqHeading';
import TermText from '#components/domain/Faq/TermText';
import FaqList from '#components/domain/FaqList';
import Link from '#components/Link';
import TabPage from '#components/TabPage';
import { DREF_TYPE_IMMINENT } from '#utils/constants';
import {
    DREF_AA_MANUAL_URL,
    DREF_ANTICIPATORY_GUIDANCE_URL,
    getNewDrefRouteState,
} from '#utils/domain/dref';

import EapMap from './EapMap';
import EapTable from './EapTable';
import ImminentDrefMap from './ImminentDrefMap';
import ImminentDrefTable from './ImminentDrefTable';

import i18n from './i18n.json';

type SubTab = 'imminent' | 'eap';

const imminentDrefRouteState = getNewDrefRouteState(DREF_TYPE_IMMINENT);

// eslint-disable-next-line import/prefer-default-export
export function Component() {
    const strings = useTranslation(i18n);
    const [activeSubTab, setActiveSubTab] = useState<SubTab>('imminent');

    return (
        <TabPage>
            <ListView
                layout="grid"
                numPreferredGridColumns={3}
                spacing="lg"
                minGridColumnSize="16rem"
            >
                <ListView layout="block">
                    <Description>
                        <ListView
                            layout="block"
                            spacing="sm"
                        >
                            <p>{strings.anticipatoryIntroOne}</p>
                            <p>{strings.anticipatoryIntroTwo}</p>
                        </ListView>
                    </Description>
                    <ListView
                        withStartAlignment
                        withWrap
                    >
                        <DrefDocumentLink
                            name="fullAnticipatoryGuidance"
                            url={DREF_ANTICIPATORY_GUIDANCE_URL}
                            label={strings.fullAnticipatoryGuidanceLink}
                        />
                    </ListView>
                </ListView>
                <GridLayoutItem columnSpan={2}>
                    <ListView
                        layout="grid"
                        minGridColumnSize="16rem"
                    >
                        <Container
                            heading={strings.imminentCardHeading}
                            withHeaderBorder
                            withBackground
                            withShadow
                            withPadding
                            footer={(
                                <Link
                                    to="newDrefApplicationForm"
                                    state={imminentDrefRouteState}
                                    styleVariant="outline"
                                    colorVariant="primary"
                                >
                                    {strings.imminentCardButton}
                                </Link>
                            )}
                        >
                            {strings.imminentCardText}
                        </Container>
                        <Container
                            heading={strings.eapCardHeading}
                            withHeaderBorder
                            withBackground
                            withShadow
                            withPadding
                            footer={(
                                <Link
                                    to="newEapDevelopmentRegistration"
                                    styleVariant="outline"
                                    colorVariant="primary"
                                >
                                    {strings.eapCardButton}
                                </Link>
                            )}
                        >
                            {strings.eapCardText}
                        </Container>
                    </ListView>
                </GridLayoutItem>
            </ListView>
            <Tabs
                value={activeSubTab}
                onChange={setActiveSubTab}
                styleVariant="pill"
            >
                <TabList>
                    <Tab name="imminent">{strings.subTabImminent}</Tab>
                    <Tab name="eap">{strings.subTabEap}</Tab>
                </TabList>
                <TabPanel name="imminent">
                    <ListView
                        layout="block"
                        spacing="2xl"
                    >
                        <Description>{strings.imminentTabDescription}</Description>
                        <FaqList>
                            <Faq
                                name="imminentDref"
                                question={strings.faqImminentDrefQuestion}
                            >
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                >
                                    <p>{strings.faqImminentDrefIntro}</p>
                                    <p>{strings.faqImminentDrefScope}</p>
                                    <ul>
                                        <li>{strings.faqImminentDrefBulletNotYet}</li>
                                        <li>{strings.faqImminentDrefBulletUnfolding}</li>
                                    </ul>
                                    <p>{strings.faqImminentDrefOutro}</p>
                                </ListView>
                            </Faq>
                            <Faq
                                name="imminentCharacteristics"
                                question={strings.faqImminentCharacteristicsQuestion}
                            >
                                <ul>
                                    <li>
                                        <TermText
                                            term={strings.faqImminentCharTimeframeTerm}
                                            variant="bold"
                                        >
                                            {strings.faqImminentCharTimeframeDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqImminentCharTriggerTerm}
                                            variant="bold"
                                        >
                                            {strings.faqImminentCharTriggerDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqImminentCharThresholds}
                                            variant="bold"
                                        />
                                        <ul>
                                            <li>{strings.faqImminentCharThresholdsNoRrp}</li>
                                            <li>{strings.faqImminentCharThresholdsWithRrp}</li>
                                        </ul>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqImminentCharComponentsTerm}
                                            variant="bold"
                                        />
                                        {' '}
                                        <TermText
                                            term={strings.faqImminentCharComponentsNoReadiness}
                                            variant="underline"
                                        />
                                        {' '}
                                        {strings.faqImminentCharComponentsFocus}
                                        <ul>
                                            <li>
                                                <TermText
                                                    term={strings.faqImminentCharEarlyActionTerm}
                                                    variant="bold"
                                                >
                                                    {strings.faqImminentCharEarlyActionDetail}
                                                </TermText>
                                            </li>
                                            <li>
                                                <TermText
                                                    term={strings.faqImminentCharEarlyResponseTerm}
                                                    variant="bold"
                                                >
                                                    {strings.faqImminentCharEarlyResponseDetail}
                                                </TermText>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </Faq>
                            <Faq
                                name="imminentProcess"
                                question={strings.faqImminentProcessQuestion}
                            >
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqImminentProcessPlanningHeading}
                                    </FaqHeading>
                                    <ul>
                                        <li>{strings.faqImminentProcessPlanningTemplate}</li>
                                        <li>{strings.faqImminentProcessPlanningTiming}</li>
                                        <li>{strings.faqImminentProcessPlanningBudget}</li>
                                        <li>{strings.faqImminentProcessPlanningBankLetter}</li>
                                        <li>{strings.faqImminentProcessPlanningSubmit}</li>
                                    </ul>
                                </ListView>
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqImminentProcessImplementationHeading}
                                    </FaqHeading>
                                    <ul>
                                        <li>{strings.faqImminentProcessImplBegin}</li>
                                        <li>{strings.faqImminentProcessImplEnsure}</li>
                                        <li>{strings.faqImminentProcessImplFunds}</li>
                                        <li>{strings.faqImminentProcessImplGovernment}</li>
                                        <li>{strings.faqImminentProcessImplCoordinate}</li>
                                    </ul>
                                </ListView>
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqImminentProcessReportingHeading}
                                    </FaqHeading>
                                    <ul>
                                        <li>
                                            <TermText
                                                term={strings.faqImminentProcessScenarioOneTerm}
                                                variant="underline"
                                            >
                                                {strings.faqImminentProcessScenarioOneDetail}
                                            </TermText>
                                            <ul>
                                                <li>
                                                    {strings.faqImminentProcessScenarioOneReport}
                                                </li>
                                                <li>
                                                    {strings.faqImminentProcessScenarioOneBalance}
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <TermText
                                                term={strings.faqImminentProcessScenarioTwoTerm}
                                                variant="underline"
                                            >
                                                {strings.faqImminentProcessScenarioTwoDetail}
                                            </TermText>
                                            <ul>
                                                <li>
                                                    {strings.faqImminentProcessScenarioTwoRequest}
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </ListView>
                            </Faq>
                        </FaqList>
                        <DrefDecisionTreeCallout />
                        <ImminentDrefMap />
                        <ImminentDrefTable />
                        <DrefKeyResources variant="anticipatory" />
                    </ListView>
                </TabPanel>
                <TabPanel name="eap">
                    <ListView
                        layout="block"
                        spacing="xl"
                    >
                        <Description>
                            <p>{strings.eapTabDescriptionLead}</p>
                            <ul>
                                <li>{strings.eapTabDescriptionEap}</li>
                                <li>{strings.eapTabDescriptionSeap}</li>
                            </ul>
                        </Description>
                        <FaqList>
                            <Faq
                                name="fullEap"
                                question={strings.faqFullEapQuestion}
                            >
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                >
                                    <p>{strings.faqFullEapIntro}</p>
                                    <p>{strings.faqFullEapIncludes}</p>
                                    <ul>
                                        <li>{strings.faqFullEapBulletHazard}</li>
                                        <li>{strings.faqFullEapBulletTrigger}</li>
                                        <li>{strings.faqFullEapBulletActivities}</li>
                                        <li>{strings.faqFullEapBulletRoles}</li>
                                        <li>{strings.faqFullEapBulletBudget}</li>
                                    </ul>
                                    <p>{strings.faqFullEapOutro}</p>
                                </ListView>
                            </Faq>
                            <Faq
                                name="eapCharacteristics"
                                question={strings.faqEapCharacteristicsQuestion}
                            >
                                <ul>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharPurposeTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharPurposeDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharTimeframeTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharTimeframeDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharCoverageTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharCoverageDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharScaleTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharScaleDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharTriggerTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharTriggerDetail}
                                        </TermText>
                                        <ul>
                                            <li>{strings.faqEapCharTriggerEstablished}</li>
                                            <li>{strings.faqEapCharTriggerContext}</li>
                                            <li>{strings.faqEapCharTriggerDatabase}</li>
                                        </ul>
                                    </li>
                                    <li>{strings.faqEapCharTriggerReached}</li>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharBudgetTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharBudgetDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqEapCharComponentsTerm}
                                            variant="bold"
                                        >
                                            {strings.faqEapCharComponentsDetail}
                                        </TermText>
                                        <ul>
                                            <li>
                                                <TermText
                                                    term={strings.faqEapCharPrepositionedTerm}
                                                    variant="underline"
                                                >
                                                    {strings.faqEapCharPrepositionedDetail}
                                                </TermText>
                                            </li>
                                            <li>
                                                <TermText
                                                    term={strings.faqEapCharReadinessTerm}
                                                    variant="underline"
                                                >
                                                    {strings.faqEapCharReadinessDetail}
                                                </TermText>
                                            </li>
                                            <li>
                                                <TermText
                                                    term={strings.faqEapCharEarlyActionTerm}
                                                    variant="underline"
                                                >
                                                    {strings.faqEapCharEarlyActionDetail}
                                                </TermText>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </Faq>
                            <Faq
                                name="seap"
                                question={strings.faqSeapQuestion}
                            >
                                <p>{strings.faqSeapIntro}</p>
                                <ul>
                                    <li>{strings.faqSeapBulletNoPartner}</li>
                                    <li>{strings.faqSeapBulletSmallerScale}</li>
                                    <li>{strings.faqSeapBulletNewHazard}</li>
                                </ul>
                            </Faq>
                            <Faq
                                name="seapCharacteristics"
                                question={strings.faqSeapCharacteristicsQuestion}
                            >
                                <ul>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharPurposeTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharPurposeDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharTimeframeTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharTimeframeDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharCoverageTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharCoverageDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharScaleTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharScaleDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharTriggerTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharTriggerDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharBudgetTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharBudgetDetail}
                                        </TermText>
                                    </li>
                                    <li>
                                        <TermText
                                            term={strings.faqSeapCharComponentsTerm}
                                            variant="bold"
                                        >
                                            {strings.faqSeapCharComponentsDetail}
                                        </TermText>
                                    </li>
                                </ul>
                            </Faq>
                            <Faq
                                name="eapProcess"
                                question={strings.faqEapProcessQuestion}
                            >
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqEapProcessDevelopmentHeading}
                                    </FaqHeading>
                                    <ol>
                                        <li>{strings.faqEapProcessDevRegister}</li>
                                        <li>
                                            {strings.faqEapProcessDevAccessForm}
                                            &nbsp;
                                            <Link
                                                external
                                                href={DREF_AA_MANUAL_URL}
                                                withUnderline
                                                withLinkIcon
                                            >
                                                {strings.faqEapProcessDevAccessFormLink}
                                            </Link>
                                            .
                                        </li>
                                        <li>
                                            {strings.faqEapProcessDevSubmit}
                                            <ul>
                                                <li>{strings.faqEapProcessDevStatusUnderReview}</li>
                                                <li>{strings.faqEapProcessDevInitialReview}</li>
                                            </ul>
                                        </li>
                                        <li>
                                            {strings.faqEapProcessDevAddressComments}
                                            <p>
                                                <TermText
                                                    term={strings.faqNoteTerm}
                                                    variant="underline"
                                                >
                                                    {/* eslint-disable-next-line max-len */}
                                                    {strings.faqEapProcessDevNoteBelowStandardsDetail}
                                                </TermText>
                                            </p>
                                        </li>
                                        <li>
                                            {strings.faqEapProcessDevNextVersions}
                                            <ul>
                                                <li>{strings.faqEapProcessDevValidate}</li>
                                                <li>{strings.faqEapProcessDevSupplementary}</li>
                                            </ul>
                                            <p>
                                                <TermText
                                                    term={strings.faqNoteTerm}
                                                    variant="underline"
                                                >
                                                    {strings.faqEapProcessDevNoteIterationsDetail}
                                                </TermText>
                                            </p>
                                        </li>
                                        <li>{strings.faqEapProcessDevBudgetValidation}</li>
                                        <li>{strings.faqEapProcessDevApproval}</li>
                                    </ol>
                                </ListView>
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqEapProcessManagementHeading}
                                    </FaqHeading>
                                    <ListView
                                        layout="block"
                                        withSpacingOpticalCorrection
                                    >
                                        <ListView
                                            layout="block"
                                            withSpacingOpticalCorrection
                                            spacing="2xs"
                                        >
                                            <FaqHeading variant="subsection">
                                                {strings.faqEapProcessAgreementHeading}
                                            </FaqHeading>
                                            <p>{strings.faqEapProcessAgreementSign}</p>
                                            <p>{strings.faqEapProcessAgreementStatus}</p>
                                        </ListView>
                                        <ListView
                                            layout="block"
                                            withSpacingOpticalCorrection
                                            spacing="2xs"
                                        >
                                            <FaqHeading variant="subsection">
                                                {strings.faqEapProcessStockHeading}
                                            </FaqHeading>
                                            <ul>
                                                <li>{strings.faqEapProcessStockProcure}</li>
                                                <li>{strings.faqEapProcessStockReadiness}</li>
                                            </ul>
                                        </ListView>
                                        <ListView
                                            layout="block"
                                            withSpacingOpticalCorrection
                                            spacing="2xs"
                                        >
                                            <FaqHeading variant="subsection">
                                                {strings.faqEapProcessTriggerHeading}
                                            </FaqHeading>
                                            <ul>
                                                <li>{strings.faqEapProcessTriggerMonitor}</li>
                                                <li>
                                                    {strings.faqEapProcessTriggerAnnounce}
                                                    <p>
                                                        <TermText
                                                            term={strings.faqNoteTerm}
                                                            variant="underline"
                                                        >
                                                            {/* eslint-disable-next-line max-len */}
                                                            {strings.faqEapProcessTriggerNoteExceptionalDetail}
                                                        </TermText>
                                                    </p>
                                                </li>
                                                <li>{strings.faqEapProcessTriggerImplement}</li>
                                            </ul>
                                        </ListView>
                                    </ListView>
                                </ListView>
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqEapProcessReportingHeading}
                                    </FaqHeading>
                                    <ul>
                                        <li>{strings.faqEapProcessReportingAnnual}</li>
                                        <li>
                                            <TermText
                                                term={strings.faqEapProcessReportingIfActivated}
                                                variant="underline"
                                            />
                                            <ul>
                                                <li>{strings.faqEapProcessReportingWorkshop}</li>
                                                <li>
                                                    {strings.faqEapProcessReportingActivationReport}
                                                </li>
                                            </ul>
                                        </li>
                                        <li>{strings.faqEapProcessReportingFinalReport}</li>
                                    </ul>
                                </ListView>
                                <ListView
                                    layout="block"
                                    withSpacingOpticalCorrection
                                    spacing="sm"
                                >
                                    <FaqHeading variant="section">
                                        {strings.faqEapProcessRevisionHeading}
                                    </FaqHeading>
                                    <ul>
                                        <li>{strings.faqEapProcessRevisionRevise}</li>
                                        <li>{strings.faqEapProcessRevisionResubmit}</li>
                                    </ul>
                                </ListView>
                            </Faq>
                        </FaqList>
                        <DrefDecisionTreeCallout />
                        <EapMap />
                        <EapTable />
                        <DrefKeyResources variant="anticipatory" />
                    </ListView>
                </TabPanel>
            </Tabs>
        </TabPage>
    );
}

Component.displayName = 'DrefAnticipatoryPillar';
