const country = {
    countryTitle: 'IFRC GO - Country',
    // not used -   countryListInRegion: ' Countries in this Region',
    // not used -   countryListViewActiveOnly: 'View only active operations',
    countryListActiveOperation: 'IFRC-Supported Operation',
    countryListActiveOperations: 'IFRC-Supported Operations',
    countryPreparednessTitle: 'Preparedness',
    countryOperationsTab: 'Operations',
    country3WTab: '3W',
    countryPreparednessTab: 'Preparedness',
    countryAdditionalInfoTab: 'Additional Data',
    countryCountryPlanTab: 'Country Plan',

    countryPlanTitle: '{countryName} Country Plan',

    activeCountryPlanTitle: 'Active Country Plan',
    countryPlanStrategicPrioritiesTableHeading: 'Strategic Priorities',
    countryPlanPeopleTargeted: 'People Targeted',
    countryPlanStrategicPriority: 'Strategic Priority',
    countryPlanMembershipCoordinationTableTitle: 'Membership Coordination',
    countryPlanLoadFailureMessage: 'Failed to load the Country Plan!',
    countryPlanDownloadPlan: '{countryName} Country Plan',
    countryPlanDownloadPlanInternal: '{countryName} Internal Plan',
    countryPlanKeyFigureRequestedAmount: 'Federation-Wide Requested Amount (CHF)',
    countryPlanKeyFigurePeopleTargeted: 'People Targeted',
    countryPlanNameOfPNS: 'Name of Partner National Society',
    countryPlanNoCountryPlan: 'This country hasn\'t published any Country Plan yet!',
    countryTableDate: 'Start Date',
    countryTableName: 'Name',
    countryTableEmergency: 'Emergency',
    countryTableDisasterType: 'Disaster Type',
    countryTableRequestAmount: 'Requested Amount',
    countryTableFundedAmount: 'Funding (CHF)',
    countryTableActive: 'Active',
    countryTableReportingNS: 'Reporting NS',
    countryTablePrimarySector: 'Activity sector',
    countryTableStatus: 'Status',
    countryTableProgrammeType: 'Type',
    countryTableTargetTotal: 'Total people targeted',
    countryTableReachedTotal: 'Total people reached',
    countryTableBudgetTotal: 'Total budget',
    countryTableProjectCount: '{projectCount} projects',
    countryEditCountry: 'Edit Country',
    // not used -   countryInformScore: 'Inform Score: ',
    nsActivityReporting: 'Reporting NS',
    countryPreparednessPhaseOutcomes: 'PER related uploaded documents',
    nsActivityReportingPlaceholder: 'Select Who (Reporting NS)',
    nsActivitySector: 'Activity',
    nsActivitySectorPlaceholder: 'Select What (Sector)',
    nsActivityCountry: 'Receiving NS',
    nsActivityCountryPlaceholder: 'Select Where (Country)',
    activityDetailsPlanned: 'planned',
    activityDetailsOngoing: 'ongoing',
    activityDetailsCompleted: 'completed',
    activityDetailsActiveNationalCount: 'Active National Societies',
    supportingNSListProjects: '{noOfProjects} projects',
    countryOverviewTab: 'Country Profile',
    countryProfileKeyDocumentsTitle: 'Key Documents',
    countryProfileExternalSourcesTitle: 'External Sources',
    countryProfileDateRange: 'Date Range',
    countryProfileSearchPlaceholder: 'Search',
    countryMapDownloadedTitle: 'Movement activities',

};

export type CountryStrings = typeof country;

export default country;
