import {
    Container,
    TextOutput,
} from '@ifrc-go/ui';
import { useTranslation } from '@ifrc-go/ui/hooks';
import {
    numericIdSelector,
    stringNameSelector,
    stringValueSelector,
} from '@ifrc-go/ui/utils';

import DiffWrapper from '#components/DiffWrapper';
import useCountry from '#hooks/domain/useCountry';
import useGlobalEnums from '#hooks/domain/useGlobalEnums';
import {
    GoApiResponse,
    useRequest,
} from '#utils/restRequest';

import {
    PartialLocalUnits,
    TYPE_HEALTH_CARE,
} from '../LocalUnitsFormModal/LocalUnitsForm/schema';
import MultiSelectOutput from './MultiSelectOutput';
import SelectOutput from './SelectOutput';

import i18n from './i18n.json';

type LocalUnitResponse = GoApiResponse<'/api/v2/local-units/{id}/'>;
type VisibilityOptions = NonNullable<GoApiResponse<'/api/v2/global-enums/'>['api_visibility_choices']>[number]

interface Props{
    oldValues: LocalUnitResponse | undefined;
    value: PartialLocalUnits | undefined;
}

const visibilityKeySelector = (option: VisibilityOptions) => option.key;

function LocalUnitView(props: Props) {
    const {
        oldValues,
        value,
    } = props;

    const strings = useTranslation(i18n);
    const { api_visibility_choices: visibilityOptions } = useGlobalEnums();
    const countries = useCountry();
    const {
        response: localUnitsOptions,
    } = useRequest({
        url: '/api/v2/local-units-options/',
    });

    return (
        <Container
            contentViewType="vertical"
        >
            <DiffWrapper
                showOnlyDiff
                value={value?.type}
                oldValue={oldValues?.type}
                enabled
            >
                <SelectOutput
                    label={strings.type}
                    options={localUnitsOptions?.type}
                    value={value?.type}
                    keySelector={numericIdSelector}
                    labelSelector={stringNameSelector}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.visibility}
                oldValue={oldValues?.visibility}
                enabled
            >
                <SelectOutput
                    label={strings.visibility}
                    options={visibilityOptions}
                    value={value?.visibility}
                    keySelector={visibilityKeySelector}
                    labelSelector={stringValueSelector}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                enabled
                oldValue={oldValues?.location_json?.lat}
                value={value?.location_json?.lat}
            >
                <TextOutput
                    strongLabel
                    label={strings.latitude}
                    value={value?.location_json?.lat}
                    valueType="number"
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                enabled
                oldValue={oldValues?.location_json?.lng}
                value={value?.location_json?.lng}
            >
                <TextOutput
                    strongLabel
                    label={strings.longitude}
                    value={value?.location_json?.lng}
                    valueType="number"
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.date_of_data}
                oldValue={oldValues?.date_of_data}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.dateOfUpdate}
                    value={value?.date_of_data}
                    valueType="date"
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.subtype}
                oldValue={oldValues?.subtype}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.subtype}
                    value={value?.subtype}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.english_branch_name}
                oldValue={oldValues?.english_branch_name}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.localUnitNameEn}
                    value={value?.english_branch_name}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.local_branch_name}
                oldValue={oldValues?.local_branch_name}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.localUnitNameLocal}
                    value={value?.local_branch_name}
                />
            </DiffWrapper>
            {value?.type !== TYPE_HEALTH_CARE && (
                <DiffWrapper
                    showOnlyDiff
                    value={value?.level}
                    oldValue={oldValues?.level}
                    enabled
                >
                    <SelectOutput
                        label={strings.coverage}
                        options={localUnitsOptions?.level}
                        value={value?.level}
                        keySelector={numericIdSelector}
                        labelSelector={stringNameSelector}
                    />
                </DiffWrapper>
            )}
            {value?.type !== TYPE_HEALTH_CARE && (
                <>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.focal_person_en}
                        oldValue={oldValues?.focal_person_en}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.focalPersonEn}
                            value={value?.focal_person_en}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.focal_person_loc}
                        oldValue={oldValues?.focal_person_loc}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.focalPersonLocal}
                            value={value?.focal_person_loc}
                        />
                    </DiffWrapper>
                </>
            )}
            {value?.type !== TYPE_HEALTH_CARE && (
                <>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.source_en}
                        oldValue={oldValues?.source_en}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.sourceEn}
                            value={value?.source_en}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.source_loc}
                        oldValue={oldValues?.source_loc}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.sourceLocal}
                            value={value?.source_loc}
                        />
                    </DiffWrapper>
                </>
            )}
            {value?.type === TYPE_HEALTH_CARE && (
                <>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.affiliation}
                        oldValue={oldValues?.health?.affiliation}
                        enabled
                    >
                        <SelectOutput
                            label={strings.affiliation}
                            options={localUnitsOptions?.affiliation}
                            value={value?.health?.affiliation}
                            keySelector={numericIdSelector}
                            labelSelector={stringNameSelector}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.other_affiliation}
                        oldValue={oldValues?.health?.other_affiliation}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.otherAffiliation}
                            value={value?.health?.other_affiliation}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.functionality}
                        oldValue={oldValues?.health?.functionality}
                        enabled
                    >
                        <SelectOutput
                            label={strings.functionality}
                            options={localUnitsOptions?.functionality}
                            value={value?.health?.functionality}
                            keySelector={numericIdSelector}
                            labelSelector={stringNameSelector}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.hospital_type}
                        oldValue={oldValues?.health?.hospital_type}
                        enabled
                    >
                        <SelectOutput
                            label={strings.hospitalType}
                            options={localUnitsOptions?.hospital_type}
                            value={value?.health?.hospital_type}
                            keySelector={numericIdSelector}
                            labelSelector={stringNameSelector}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.is_teaching_hospital}
                        oldValue={
                            oldValues?.health?.is_teaching_hospital
                        }
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.teachingHospital}
                            value={value?.health?.is_teaching_hospital}
                            valueType="boolean"
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.is_teaching_hospital}
                        oldValue={
                            oldValues?.health?.is_teaching_hospital
                        }
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.inPatientCapacity}
                            value={value?.health?.is_in_patient_capacity}
                            valueType="boolean"
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.is_teaching_hospital}
                        oldValue={
                            oldValues?.health?.is_teaching_hospital
                        }
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.isolationRoomsWards}
                            value={value?.health?.is_isolation_rooms_wards}
                            valueType="boolean"
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.country}
                        oldValue={oldValues?.country}
                        enabled
                    >
                        <SelectOutput
                            label={strings.country}
                            options={countries}
                            value={value?.country}
                            keySelector={numericIdSelector}
                            labelSelector={stringNameSelector}
                        />
                    </DiffWrapper>
                </>
            )}
            <DiffWrapper
                showOnlyDiff
                value={value?.address_en}
                oldValue={oldValues?.address_en}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.addressEn}
                    value={value?.address_en}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.address_loc}
                oldValue={oldValues?.address_loc}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.addressLocal}
                    value={value?.address_loc}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.city_en}
                oldValue={oldValues?.city_en}
                enabled
            >
                <TextOutput
                    label={strings.localityEn}
                    value={value?.city_en}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.city_loc}
                oldValue={oldValues?.city_loc}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.localityLocal}
                    value={value?.city_loc}
                />
            </DiffWrapper>
            <DiffWrapper
                showOnlyDiff
                value={value?.postcode}
                oldValue={oldValues?.postcode}
                enabled
            >
                <TextOutput
                    strongLabel
                    label={strings.postCode}
                    value={value?.postcode}
                />
            </DiffWrapper>
            {value?.type !== TYPE_HEALTH_CARE && (
                <>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.phone}
                        oldValue={oldValues?.phone}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.phone}
                            value={value?.phone}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.email}
                        oldValue={oldValues?.email}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.email}
                            value={value?.email}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.link}
                        oldValue={oldValues?.link}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.website}
                            value={value?.link}
                        />
                    </DiffWrapper>
                </>
            )}
            {value?.type === TYPE_HEALTH_CARE && (
                <>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.health_facility_type}
                        oldValue={oldValues?.health?.health_facility_type}
                        enabled
                    >
                        <SelectOutput
                            label={strings.healthFacilityType}
                            options={localUnitsOptions?.health_facility_type}
                            value={value?.health?.health_facility_type}
                            keySelector={numericIdSelector}
                            labelSelector={stringNameSelector}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.general_medical_services}
                        oldValue={oldValues?.health?.general_medical_services}
                        enabled
                    >
                        <MultiSelectOutput
                            label={strings.generalMedicalServices}
                            options={localUnitsOptions?.general_medical_services}
                            value={value?.health?.general_medical_services}
                            keySelector={numericIdSelector}
                            labelSelector={stringNameSelector}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.focal_point_position}
                        oldValue={oldValues?.health?.focal_point_position}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.focalPointPosition}
                            value={value?.health?.focal_point_position}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.focal_point_email}
                        oldValue={oldValues?.health?.focal_point_email}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.focalPointEmail}
                            value={value?.health?.focal_point_email}
                        />
                    </DiffWrapper>
                    <DiffWrapper
                        showOnlyDiff
                        value={value?.health?.focal_point_phone_number}
                        oldValue={oldValues?.health?.focal_point_phone_number}
                        enabled
                    >
                        <TextOutput
                            strongLabel
                            label={strings.focalPointPhoneNumber}
                            value={value?.health?.focal_point_phone_number}
                        />
                    </DiffWrapper>
                </>
            )}
        </Container>
    );
}

export default LocalUnitView;
