// eslint-disable-next-line @typescript-eslint/ban-ts-comment
 // @ts-nocheck
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/Application": {
    get: operations["Application_List"];
    post: operations["Application_Register"];
  };
  "/api/Application/{applicationId}": {
    get: operations["Application_Get"];
    put: operations["Application_Update"];
  };
  "/api/Application/{applicationId}/Key": {
    get: operations["Key_List"];
  };
  "/api/Application/{applicationId}/Page": {
    get: operations["Page_List"];
  };
  "/api/Application/{applicationId}/Translation": {
    get: operations["Translation_ListTranslations"];
    post: operations["Translation_CreateTranslation"];
  };
  "/api/Application/{applicationId}/Translation/{translationId}": {
    get: operations["Translation_GetTranslation"];
    put: operations["Translation_UpdateTranslation"];
    delete: operations["Translation_DeleteTranslation"];
  };
  "/api/Application/{applicationId}/Translation/checkimport": {
    post: operations["Translation_CheckImport"];
  };
  "/api/Application/{applicationId}/Translation/export": {
    get: operations["Translation_ExportTranslations"];
  };
  "/api/Application/{applicationId}/Translation/fullappimport": {
    post: operations["Translation_FullAppImport"];
  };
  "/api/Application/{applicationId}/Translation/fullappimport/{importTaskId}/status": {
    get: operations["Translation_FullAppImportStatus"];
  };
  "/api/Application/{applicationId}/Translation/import": {
    post: operations["Translation_ImportTranslations"];
  };
  "/api/Application/{applicationId}/TranslationKey": {
    get: operations["TranslationKey_List"];
  };
  "/api/Application/{applicationId}/TranslationKey/{translationKeyId}": {
    get: operations["TranslationKey_Get"];
  };
  "/api/AutomaticTranslation": {
    post: operations["AutomaticTranslation_StartAutomaticTranslation"];
  };
  "/api/Detect": {
    post: operations["Home_Detect"];
  };
  "/api/Language": {
    get: operations["Language_List"];
  };
  "/api/Translate": {
    post: operations["Home_Translate"];
  };
}

export type webhooks = Record<string, never>;

export interface components<TMode extends 'read' | 'write' | 'none' = 'none'> {
  schemas: {
    ApplicationRegistrationViewModel: {
      /** Format: int32 */
      applicationId: number;
      automaticTranslationEnabled?: boolean;
      languageCodes?: string[];
      name: string;
    };
    ApplicationUpdateViewModel: {
      automaticTranslationEnabled?: boolean;
      languageCodes?: string[];
      name: string;
    };
    ApplicationViewModel: {
      automaticTranslationEnabled?: boolean;
      /** Format: int32 */
      id?: number;
      languages: components<TMode>["schemas"]["LanguageViewModel"][];
      name: string;
    };
    DetectionRequestModel: {
      text?: string;
    };
    DetectionResult: components<TMode>["schemas"]["DetectionResultBase"] & {
      alternatives?: components<TMode>["schemas"]["DetectionResultBase"][];
    };
    DetectionResultBase: {
      isTranslationSupported?: boolean;
      isTransliterationSupported?: boolean;
      language?: string;
      /** Format: float */
      score?: number;
    };
    LanguageViewModel: {
      code?: string;
      isActive?: boolean;
      localeName?: string | null;
      name?: string;
    };
    ListResultViewModelOfTranslationKeyViewModel: {
      /** Format: int64 */
      count?: number;
      page?: components<TMode>["schemas"]["PagingViewModel"];
      values?: components<TMode>["schemas"]["TranslationKeyViewModel"][];
    };
    ListResultViewModelOfTranslationViewModel: {
      /** Format: int64 */
      count?: number;
      page?: components<TMode>["schemas"]["PagingViewModel"];
      values?: components<TMode>["schemas"]["TranslationViewModel"][];
    };
    PagingViewModel: {
      /** Format: int32 */
      limit?: number;
      /** Format: int32 */
      offset?: number;
    };
    ProblemDetails: {
      detail?: string | null;
      instance?: string | null;
      /** Format: int32 */
      status?: number | null;
      title?: string | null;
      type?: string | null;
      [key: string]: (Record<string, unknown> | null) | undefined;
    };
    TranslationConfig: {
      allowedAddresses?: string | null;
      apikey?: string;
      disabled?: boolean;
      endPoint?: string;
      /** Format: int32 */
      id?: number;
      key1?: string;
      key2?: string;
      region?: string;
    };
    TranslationCreateViewModel: {
      keyName: string;
      languageCode: string;
      page: string;
      value: string;
    };
    TranslationImportAction: {
      isSuccess?: boolean;
      key?: string;
      languageCode?: string | null;
      message?: string;
      newValue?: string | null;
      originalValue?: string | null;
      page?: string;
    };
    TranslationImportResult: {
      isSuccess?: boolean;
      message?: string;
      translationActions?: components<TMode>["schemas"]["TranslationImportAction"][];
    };
    TranslationKeyDetailsTranslationViewModel: {
      /** Format: int32 */
      id?: number;
      isAutomaticTranslation?: boolean;
      languageCode?: string;
      value?: string;
    };
    TranslationKeyDetailsViewModel: {
      /** Format: int32 */
      applicationId?: number;
      applicationName?: string;
      /** Format: int32 */
      id?: number;
      name?: string;
      page?: string;
      values?: components<TMode>["schemas"]["TranslationKeyDetailsTranslationViewModel"][];
    };
    TranslationKeyViewModel: {
      /** Format: int32 */
      applicationId?: number;
      /** Format: int32 */
      id?: number;
      name?: string;
      page?: string;
      translatedTo?: string[];
    };
    TranslationRequestModel: {
      from?: string | null;
      text?: string;
      textType?: string | null;
      to?: string;
    };
    TranslationUpdateViewModel: {
      value: string;
    };
    TranslationViewModel: {
      /** Format: int32 */
      applicationId?: number;
      applicationName?: string;
      /** Format: int32 */
      id?: number;
      isAutomaticTranslation?: boolean;
      /** Format: int32 */
      keyId?: number;
      keyName?: string;
      keyPage?: string;
      languageCode?: string;
      languageName?: string;
      value?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  Application_List: {
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["ApplicationViewModel"][];
        };
      };
    };
  };
  Application_Register: {
    requestBody: {
      content: {
        "application/json": components<'write'>["schemas"]["ApplicationRegistrationViewModel"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  Application_Get: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["ApplicationViewModel"];
        };
      };
    };
  };
  Application_Update: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components<'write'>["schemas"]["ApplicationUpdateViewModel"];
      };
    };
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Key_List: {
    parameters: {
      query?: {
        page?: string | null;
      };
      path: {
        applicationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  Page_List: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  Translation_ListTranslations: {
    parameters: {
      query?: {
        KeyName?: string | null;
        KeyPage?: string | null;
        LanguageCode?: string | null;
        TranslationId?: number | null;
        Offset?: number;
        Limit?: number | null;
        Value?: string | null;
      };
      path: {
        applicationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["ListResultViewModelOfTranslationViewModel"];
        };
      };
    };
  };
  Translation_CreateTranslation: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components<'write'>["schemas"]["TranslationCreateViewModel"];
      };
    };
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Translation_GetTranslation: {
    parameters: {
      path: {
        applicationId: number;
        translationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationViewModel"];
        };
      };
      404: {
        content: {
          "application/json": components<'read'>["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  Translation_UpdateTranslation: {
    parameters: {
      path: {
        applicationId: number;
        translationId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components<'write'>["schemas"]["TranslationUpdateViewModel"];
      };
    };
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Translation_DeleteTranslation: {
    parameters: {
      path: {
        applicationId: number;
        translationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Translation_CheckImport: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          files?: string[] | null;
        };
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationImportResult"];
        };
      };
    };
  };
  Translation_ExportTranslations: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Translation_FullAppImport: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          files?: string[] | null;
        };
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationImportResult"];
        };
      };
    };
  };
  Translation_FullAppImportStatus: {
    parameters: {
      path: {
        applicationId: number;
        importTaskId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationImportResult"];
        };
      };
    };
  };
  Translation_ImportTranslations: {
    parameters: {
      path: {
        applicationId: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          files?: string[] | null;
        };
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationImportResult"];
        };
      };
    };
  };
  TranslationKey_List: {
    parameters: {
      query?: {
        Name?: string | null;
        Page?: string | null;
        Limit?: number | null;
        Offset?: number;
      };
      path: {
        applicationId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["ListResultViewModelOfTranslationKeyViewModel"];
        };
      };
    };
  };
  TranslationKey_Get: {
    parameters: {
      path: {
        applicationId: number;
        translationKeyId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationKeyDetailsViewModel"];
        };
      };
    };
  };
  AutomaticTranslation_StartAutomaticTranslation: {
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Home_Detect: {
    parameters: {
      query?: {
        apiKey?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components<'write'>["schemas"]["DetectionRequestModel"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["DetectionResult"];
        };
      };
    };
  };
  Language_List: {
    parameters: {
      query?: {
        IsActive?: boolean | null;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["LanguageViewModel"][];
        };
      };
    };
  };
  Home_Translate: {
    parameters: {
      header?: {
        "x-api-key"?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components<'write'>["schemas"]["TranslationRequestModel"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components<'read'>["schemas"]["TranslationConfig"];
        };
      };
    };
  };
}
