const localUnitFormFieldLabels = {
    type: 'Local unit type',
    visibility: 'Visibility',
    date_of_data: 'Date of update',
    subtype: 'Sub-type',
    english_branch_name: 'Local unit name (En)',
    local_branch_name: 'Local unit name (Local)',
    level: 'Coverage',
    focal_person_en: 'Focal person (En)',
    focal_person_loc: 'Focal person (Local)',
    source_en: 'Source (En)',
    source_loc: 'Source (Local)',
    country: 'Country',
    lat: 'Latitude',
    lng: 'Longitude',
    address_en: 'Address (En)',
    address_loc: 'Address (Local)',
    city_en: 'Locality (En)',
    city_loc: 'Locality (Local)',
    postCode: 'Local unit post code',
    phone: 'Local unit phone number',
    email: 'Local unit email',
    link: 'Local unit website',
    location_json: {
        lat: 'Latitude',
        lng: 'Longitude',
    },
    health: {
        affiliation: 'Affiliation',
        other_affiliation: 'Other Affiliation',
        functionality: 'Functionality',
        is_teaching_hospital: 'Teaching Hospital',
        hospital_type: 'Hospital type',
        is_in_patient_capacity: 'In-patient capacity',
        is_isolation_rooms_wards: 'Isolation rooms wards',
        focal_point_position: 'Focal person position',
        focal_point_email: 'Focal person email',
        focal_point_phone_number: 'Focal person phone number',
        health_facility_type: 'Health Facility type',
        other_facility_type: 'Other Facility type',
        primary_health_care_center: 'Primary health care center',
        speciality: 'Specialist',
        general_medical_services: 'General medical services',
        specialized_medical_beyond_primary_level: 'Specialized medical beyond primary level',
        other_services: 'Other Services',
        blood_services: 'Blood Services',
        professional_training_facilities: 'Professional training facilities',
        number_of_isolation_rooms: 'Number of isolation rooms',
        maximum_capacity: 'Maximum capacity',
        is_cold_chain: 'Cold chain',
        ambulance_type_a: 'Ambulance Type A',
        ambulance_type_b: 'Ambulance Type B',
        ambulance_type_c: 'Ambulance Type C',
        total_number_of_human_resource: 'Total number of human resource',
        general_practitioner: 'General Practitioner',
        specialist: 'Specialist',
        residents_doctor: 'Residents doctor',
        nurse: 'Nurse',
        dentist: 'Dentist',
        nursing_aid: 'Nursing aid',
        midwife: 'Midwife',
        other_medical_heal: 'Other medical heal',
        other_profiles: 'Other profiles',
        feedback: 'Comments by the NS',
    },
};

export default localUnitFormFieldLabels;
