import { TextOutput } from '@ifrc-go/ui';
import { useTranslation } from '@ifrc-go/ui/hooks';
import { resolveToComponent } from '@ifrc-go/ui/utils';

import SurgeCatalogueContainer from '#components/domain/SurgeCatalogueContainer';
import SurgeContentContainer from '#components/domain/SurgeContentContainer';
import Link from '#components/Link';

import i18n from './i18n.json';

/** @knipignore */
// eslint-disable-next-line import/prefer-default-export
export function Component() {
    const strings = useTranslation(i18n);

    return (
        <SurgeCatalogueContainer
            heading={strings.satelliteImageryTitle}
            goBackFallbackLink="surgeCatalogueInformationManagement"
        >
            <div>{strings.satelliteImageryTextOne}</div>
            <div>{strings.satelliteImageryTextTwo}</div>
            <Link
                href="https://americanredcross.github.io/images-from-above/index.html"
                external
            >
                {strings.satelliteImageryTextThree}
            </Link>
            <div>
                {resolveToComponent(
                    strings.satelliteImageryTextFour,
                    {
                        link: (
                            <Link
                                href="https://docs.google.com/spreadsheets/d/1IGxQVIRF0PkNXNXUcEA9_dz66-U2MCPRzN5O1hol1Mg/edit#gid=1206256283"
                                external
                            >
                                {strings.thisSpreadsheetLink}
                            </Link>
                        ),
                    },
                )}
            </div>
            <SurgeContentContainer
                heading={strings.satelliteImageryDefining}
            >
                <div>
                    {resolveToComponent(
                        strings.satelliteImageryDefiningText,
                        {
                            link: (
                                <Link
                                    href="https://americanredcross.github.io/images-from-above/index.html"
                                    external
                                >
                                    {strings.imagesFromAboveLink}
                                </Link>
                            ),
                        },
                    )}
                </div>
                <ol>
                    <li>{strings.satelliteImageryDefiningListItemOne}</li>
                    <li>{strings.satelliteImageryDefiningListItemTwo}</li>
                    <li>{strings.satelliteImageryDefiningListItemThree}</li>
                    <li>{strings.satelliteImageryDefiningListItemFour}</li>
                </ol>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.satelliteImageryAnalysis}
            >
                <div>{strings.satelliteImageryAnalysisTextOne}</div>
                <div>{strings.satelliteImageryAnalysisTextTwo}</div>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.satelliteImageryUNOSATTitle}
            >
                <Link
                    href="https://www.unitar.org/maps"
                    external
                >
                    {strings.satelliteImageryUnitarLink}
                </Link>
                <div>{strings.satelliteUNOSATTextOne}</div>
                <div>{strings.satelliteUNOSATTextTwo}</div>
                <div>{strings.satelliteUNOSATTextThree}</div>
                <ol>
                    <li>{strings.satelliteUNOSATItemOne}</li>
                    <ol type="a">
                        <li>
                            {resolveToComponent(
                                strings.satelliteUNOSATItemOneListOne,
                                {
                                    link: (
                                        <Link
                                            href="https://www.unitar.org/maps"
                                            external
                                        >
                                            {strings.satelliteTheirWebsiteLink}
                                        </Link>
                                    ),
                                },
                            )}
                        </li>
                        <li>
                            {resolveToComponent(
                                strings.satelliteUNOSATItemOneListTwo,
                                {
                                    link: (
                                        <Link
                                            href="https://smcs.unosat.org/home"
                                            external
                                        >
                                            {strings.satelliteMappingCoordinationLink}
                                        </Link>
                                    ),
                                },
                            )}
                        </li>
                    </ol>
                    <li>
                        {resolveToComponent(
                            strings.satelliteUNOSATItemTwo,
                            {
                                link: (
                                    <Link
                                        href="mailto:im@ifrc.org"
                                        external
                                    >
                                        {strings.imageryImEmailLink}
                                    </Link>
                                ),
                            },
                        )}
                    </li>
                    <ol type="a">
                        <li>{strings.satelliteUNOSATItemTwoListOne}</li>
                        <li>{strings.satelliteUNOSATItemTwoListTwo}</li>
                        <li>{strings.satelliteUNOSATItemTwoListThree}</li>
                        <li>{strings.satelliteUNOSATItemTwoListFour}</li>
                        <li>{strings.satelliteUNOSATItemTwoListFive}</li>
                        <li>{strings.satelliteUNOSATItemTwoListSix}</li>
                    </ol>
                    <li>
                        {resolveToComponent(
                            strings.satelliteUNOSATItemThree,
                            {
                                link: (
                                    <Link
                                        href="https://unosat.org/products/"
                                        external
                                    >
                                        {strings.satelliteUNOSATItemThreeLink}
                                    </Link>
                                ),
                            },
                        )}
                    </li>
                    <li>{strings.satelliteUNOSATItemFour}</li>
                </ol>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.satelliteImageryAnalysis}
            >
                <Link
                    href="https://mapswipe.org"
                    external
                >
                    {strings.satelliteMapSwipeLink}
                </Link>
                <div>{strings.satelliteMapSwipeTextOne}</div>
                <ul>
                    <li>{strings.satelliteMapSwipeTextOneListOne}</li>
                    <li>{strings.satelliteMapSwipeTextOneListTwo}</li>
                </ul>
                <div>
                    {resolveToComponent(
                        strings.satelliteMapSwipeDescription,
                        {
                            emailLink: (
                                <Link
                                    href="mailto:info@mapswipe.org"
                                    external
                                >
                                    {strings.satelliteMapSwipeDescriptionEmailLink}
                                </Link>
                            ),
                            link: (
                                <Link
                                    href="https://mapswipe.org/en/index.html"
                                    external
                                >
                                    {strings.satelliteMapSwipeDescriptionOnTheWebsite}
                                </Link>
                            ),
                        },
                    )}
                </div>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.imagerySourcesTitle}
            >
                <div>{strings.imagerySourcesDescription}</div>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.imagerySourcesSubTitle}
            >
                <div>
                    {strings.imagerySourcesSubTitleDescription}
                </div>
                <ul>
                    <li>
                        {strings.imagerySourcesSubTitleItemOne}
                        <Link
                            href="https://www.maxar.com/open-data"
                            external
                        >
                            {strings.imagerySourcesSubTitleItemLink}
                        </Link>
                    </li>
                    <li>
                        {strings.imagerySourcesSubTitleItemTwo}
                        <Link
                            href="https://www.planet.com/disasterdata"
                            external
                        >
                            {strings.imagerySourcesSubTitleItemTwoLink}
                        </Link>
                    </li>
                </ul>
                <div>
                    {resolveToComponent(
                        strings.imagerySourcesSubTitleDetail,
                        {
                            link: (
                                <Link
                                    href="https://openaerialmap.org/"
                                    external
                                >
                                    {strings.imagerySourcesSubTitleDetailLink}
                                </Link>
                            ),
                        },
                    )}
                </div>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.imagerySourcesIFRCPartnerships}
            >
                <div>{strings.imagerySourcesIFRCPartnershipsDetail}</div>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.imagerySourcesInternationalSpaceTitle}
            >
                <Link
                    href="https://disasterscharter.org/web/guest/home"
                    external
                >
                    {strings.imagerySourcesDisastersCharterHomeLink}
                </Link>
                <div>{strings.imagerySourcesInternationalSpaceTextOne}</div>
                <div>{strings.imagerySourcesInternationalSpaceTextTwo}</div>
                <TextOutput
                    label={strings.imagerySourcesInternationalSpaceTextThree}
                    value={(
                        <Link
                            href="https://disasterscharter.org/web/guest/charter-activations"
                            external
                        >
                            {strings.imagerySourcesDisastersCharterLink}
                        </Link>
                    )}
                />
                <div>{strings.imagerySourcesInternationalSpaceTextFour}</div>
            </SurgeContentContainer>
            <SurgeContentContainer
                heading={strings.imageryAirbusFoundation}
            >
                <Link
                    href="https://www.intelligence-airbusds.com/airbus-foundation/"
                    external
                >
                    {strings.imageryAirbusFoundationLink}
                </Link>
                <div>{strings.imageryAirbusFoundationTextOne}</div>
                <div>
                    {resolveToComponent(
                        strings.imageryAirbusFoundationTextTwo,
                        {
                            link: (
                                <Link
                                    href="mailto:im@ifrc.org"
                                    external
                                >
                                    {strings.imageryImEmailLink}
                                </Link>
                            ),
                        },
                    )}
                </div>
                <div>{strings.imageryAirbusFoundationToCheck}</div>
                <ul>
                    <li>
                        {resolveToComponent(
                            strings.imageryAirbusFoundationListOne,
                            {
                                link: (
                                    <Link
                                        href="https://www.intelligence-airbusds.com/airbus-foundation/"
                                        external
                                    >
                                        {strings.imageryAirbusFoundationListOneLink}
                                    </Link>
                                ),
                            },
                        )}
                    </li>
                    <li>{strings.imageryAirbusFoundationListTwo}</li>
                    <ul>
                        <li>{strings.imageryAirbusFoundationListTwoItemOne}</li>
                    </ul>
                    <li>{strings.imageryAirbusFoundationListThree}</li>
                    <ul>
                        <li>{strings.imageryAirbusFoundationListThreeItemOne}</li>
                        <li>{strings.imageryAirbusFoundationListThreeItemTwo}</li>
                        <li>{strings.imageryAirbusFoundationListThreeItemThree}</li>
                        <li>{strings.imageryAirbusFoundationListThreeItemFour}</li>
                    </ul>
                    <li>{strings.imageryAirbusFoundationListFour}</li>
                    <li>{strings.imageryAirbusFoundationListFive}</li>
                    <ul>
                        <li>
                            {strings.imageryAirbusFoundationListFiveItemOne}
                        </li>
                    </ul>
                    <li>
                        {resolveToComponent(
                            strings.imageryAirbusFoundationListSix,
                            {
                                link: (
                                    <Link
                                        href="mailto:im@ifrc.org"
                                        external
                                    >
                                        {strings.imageryImEmailLink}
                                    </Link>
                                ),
                            },
                        )}
                    </li>
                    <ul>
                        <li>{strings.imageryAirbusFoundationListSixItemOne}</li>
                        <li>{strings.imageryAirbusFoundationListSixItemTwo}</li>
                        <li>{strings.imageryAirbusFoundationListSixItemThree}</li>
                        <li>{strings.imageryAirbusFoundationListSixItemFour}</li>
                        <li>{strings.imageryAirbusFoundationListSixItemFive}</li>
                    </ul>
                </ul>
                <div>{strings.imageryAirbusFoundationTextThree}</div>
            </SurgeContentContainer>
        </SurgeCatalogueContainer>
    );
}

Component.displayName = 'SurgeCatalogueInformationManagementSatelliteImagery';
