name: 'Chromatic Publish'

on:
  push:
    branches:
      - project/storybook

jobs:
  chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/go-ui-storybook
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn
      #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: packages/go-ui-storybook
