name: 'Chromatic'

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chromatic
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  pages: write
  id-token: write

jobs:
  ui:
    name: Build UI Library
    environment: 'test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies on UI library
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
      - name: Lint CSS
        run: yarn lint:css
      - name: Lint JS
        run: yarn lint:js
      - name: build  UI library
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: packages/ui/dist
  chromatic:
    name: Chromatic Deploy
    runs-on: ubuntu-latest
    needs: [ui]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: packages/ui/dist
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: "@(renovate/**|dependabot/**)"
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/go-ui-storybook
  github-pages:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: [ui]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: packages/ui/dist
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install
          build_command: yarn build-storybook
          path: packages/go-ui-storybook/storybook-static
          checkout: false
