name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_ADMIN_URL: ${{ vars.APP_ADMIN_URL }}
  APP_API_ENDPOINT: ${{ vars.APP_API_ENDPOINT }}
  APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}
  APP_MAPBOX_ACCESS_TOKEN: ${{ vars.APP_MAPBOX_ACCESS_TOKEN }}
  APP_RISK_ADMIN_URL: ${{ vars.APP_RISK_ADMIN_URL }}
  APP_RISK_API_ENDPOINT: ${{ vars.APP_RISK_API_ENDPOINT }}
  APP_SENTRY_DSN: ${{ vars.APP_SENTRY_DSN }}
  APP_SENTRY_NORMALIZE_DEPTH: ${{ vars.APP_SENTRY_NORMALIZE_DEPTH }}
  APP_SENTRY_TRACES_SAMPLE_RATE: ${{ vars.APP_SENTRY_TRACES_SAMPLE_RATE }}
  APP_SHOW_ENV_BANNER: ${{ vars.APP_SHOW_ENV_BANNER }}
  APP_TINY_API_KEY: ${{ vars.APP_TINY_API_KEY }}
  APP_TITLE: ${{ vars.APP_TITLE }}
  GITHUB_WORKFLOW: true

jobs:
  test:
    name: Run tests
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run test

        run: yarn test
  translation:
    name: Identify error with translation files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Identify error with translation files
        run: yarn lint:translation
  unimported:
    name: Identify unused files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Identify unused files
        run: yarn lint:unused
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint JS
        run: yarn lint:js
  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint CSS
        run: yarn lint:css
  # FIXME: Identify a way to generate schema before we run typecheck
  # typecheck:
  #   name: Typecheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn install --prefer-offline --frozen-lockfile

  #     - name: Typecheck
  #       run: yarn typecheck
  build:
    name: Build
    environment: 'test'
    needs: [lint, lint-css, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build
        run: yarn build
