name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_ADMIN_URL: ${{ vars.APP_ADMIN_URL }}
  APP_API_ENDPOINT: ${{ vars.APP_API_ENDPOINT }}
  APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}
  APP_MAPBOX_ACCESS_TOKEN: ${{ vars.APP_MAPBOX_ACCESS_TOKEN }}
  APP_RISK_ADMIN_URL: ${{ vars.APP_RISK_ADMIN_URL }}
  APP_RISK_API_ENDPOINT: ${{ vars.APP_RISK_API_ENDPOINT }}
  APP_SENTRY_DSN: ${{ vars.APP_SENTRY_DSN }}
  APP_SENTRY_NORMALIZE_DEPTH: ${{ vars.APP_SENTRY_NORMALIZE_DEPTH }}
  APP_SENTRY_TRACES_SAMPLE_RATE: ${{ vars.APP_SENTRY_TRACES_SAMPLE_RATE }}
  APP_SHOW_ENV_BANNER: ${{ vars.APP_SHOW_ENV_BANNER }}
  APP_TINY_API_KEY: ${{ vars.APP_TINY_API_KEY }}
  APP_TITLE: ${{ vars.APP_TITLE }}
  GITHUB_WORKFLOW: true

jobs:
  test:
    name: Run tests
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/actions-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run test
        run: pnpm test
        working-directory: app

  translation:
    name: Identify error with translation files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/actions-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Identify error with translation files
        run: pnpm lint:translation
        working-directory: app

  lint:
    name: Lint JS/CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/actions-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint JS
        run: pnpm lint

  build:
    name: Build GO Web App
    environment: 'test'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/actions-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
