name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_API_ENDPOINT: ${{ vars.APP_API_ENDPOINT }}
  APP_FDRS_AUTH: ${{ vars.APP_FDRS_AUTH }}
  APP_MAPBOX_ACCESS_TOKEN: ${{ vars.APP_MAPBOX_ACCESS_TOKEN }}
  APP_RISK_API_ENDPOINT: ${{ vars.APP_RISK_API_ENDPOINT }}
  APP_TINY_API_KEY: ${{ vars.APP_TINY_API_KEY }}
  APP_TITLE: ${{ vars.APP_TITLE }}
  GITHUB_WORKFLOW: true

jobs:
  test:
    name: Run tests
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Run test

        run: yarn test
  unimported:
    name: Find unimported files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Run unimported
        run: yarn unimported
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Lint
        run: yarn lint
  css-lint:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Css Lint
        run: yarn css-lint
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Typecheck
        run: yarn typecheck
  build:
    name: Build
    needs: [lint, css-lint, typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Build
        run: yarn build
